Main/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("",main,name="main"),
    path("send_email/", send_email, name="send_email"),
]

app_name = "main"

account/urls.py
from django.urls import path, include
from Account.views import *


urlpatterns = [
    path("login/",  AccountLogin.as_view(), name="login"),
    path("logout/", logout, name="logout"),
    path("signup/", AccountSignup.as_view(), name="signup"),
]

app_name = "account"

email_sender/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Main.urls")),
    path('accounts/', include("Account.urls")),
]

account/models.py
from django.db import models

# Create your models here.

Main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.mail import EmailMessage,send_mail
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import time

# Create your views here.


@login_required
def main(request):
    return render(request,"base.html")


@login_required
def send_email(request):
    email = request.POST["email"]
    subject = request.POST["subject"]
    message = request.POST["message"]
    name = request.user.username
    if subject and email:
        send_mail(
            subject,
            message,
            'sadravalorant@gmail.com',
            [email],
            fail_silently=False,
        )
        messages.success(request,"your email has been sent")
        return redirect("main")
    else:
        messages.error(request, "there is something wrong with your form")
        return redirect("main")

account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.views import *
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout as system_logout
from django.contrib.auth import login


# Create your views here.


def main(request):
    return render(request,"account_base.html")

class AccountLogin(LoginView):
    template_name = 'login.html'
    fields = "__all__"
    redirect_authenticated_user = True
    
    def get_success_url(self):
        messages.success(self.request,"You Have Logged In successfuly")
        return reverse_lazy("main:main")


def logout(request):
    messages.success(request, "You Have Logged Out successfuly")
    system_logout(request)
    return HttpResponseRedirect('/')

class CustomLogoutView(LogoutView):
    template_name = "todo_list/login.html"
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("main:main")

class AccountSignup(FormView):
    template_name = "register.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("main:main")

    def form_invalid(self, form):
        messages.error("Something Was Wrong With Your Form")
        return super(AccountSignup, self).form_invalid(form)
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(AccountSignup,self).form_valid(form)
    
    def get(self,*args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("main:main")
        return super(AccountSignup,self).get(*args,**kwargs)

# TODO:
# class AccountSignin():


# class AccountSignout():

Main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


                                    <!-- local files -->
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <script src="{% static 'script.js' %}"></script>

    <title>Email Sender</title>

</head>
<body>
      <nav>
    <div id="nav" class="nav-wrapper">
    <div class="image" title="Github Page"></div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">

        {% if user.is_authenticated %}
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'account:login' %}">Login</a></li>
            <li><a href="{% url 'account:signup' %}">SignUp</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <h2 class="h2">{{ message }}</h2>
            </div>
        {% endfor %}
    {% endif %}
    
</div>
{% block content %}

{% endblock content %}

{% if user.is_authenticated %}

    <div class="container">

        <div style="margin-top: 300px;" class="row">
            <form action="/send_email/" method="post" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                        <input style="cursor: not-allowed;" name="name" disabled placeholder="Placeholder" id="first_name" type="text" value="{{user.username}}" class="validate">
                        <label for="first_name">Name</label>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input  name="subject"  id="disabled" type="text" class="validate" >
                        <label for="disabled">Subject</label>
                    </div>
                </div>
                
                <div class="row">
                    <div class="input-field col s12">
                        <input id="email" name="email" type="email" class="validate">
                        <label for="email">Email</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <input id="message" name="message" type="text" >
                        <label for="message">Message</label>
                    </div>
                </div>
                
                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                    <i class="fa fa-paper-plane" aria-hidden="true"></i>
                </button>
            </form>
        </div>
    </div>
{% else %}
    <h2 style="text-align: center;">Sry But You Are Not Logged In </h2>
{% endif %}


        
</body>
</html>

Main/templates/form.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert  alert-dismissible fade show"  role="alert">
                <h2 class="h2" >{{ message }}</h2>
            </div>
        {% endfor %}
    {% endif %}
    
</div>
{% endblock content %}

account/templates/account_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>
<body>
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <h2 class="h2">{{ message }}</h2>
        </div>
        {% endfor %}
        {% endif %}
    
    </div>
    
    {% block content %}
        
    {% endblock content %}
        
</body>
</html>

account/templates/login.html
{% extends 'account_base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="container">
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input class="button" type="submit" value="Login">
        </form>
        <p>Don't have an account? <a href="{% url 'account:signup' %}">Register</a></p>
    </div>
</div>






{% endblock content %}

account/templates/register.html
{% extends 'account_base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>
<div class="container">

    <div class="card-body">
        <form method="POST">
        {% csrf_token %}
            <label>{{form.username.label}}</label>
            {{form.username}}
            
            <label>{{form.password1.label}}</label>
            {{form.password1}}
            
            <label>{{form.password2.label}}</label>
            {{form.password2}}
            <input style="margin-top:10px ;" class="button" type="submit" value="Register">
        </form>
        <p>Already have an account? <a href="">Login</a></p>
    </div>
</div>
    
    
    

{% endblock content %}